name: Vars
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose an env
        options:
        - stg
        - dev
        

jobs:
  display-variables:
    runs-on: ${{ vars.DEPLOY_RUNNER }}
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - name: Use variables
      run: |
        echo "deployment runner : $DEPLOY_RUNNER"
      env:
        DEPLOY_RUNNER: ${{ vars.DEPLOY_RUNNER }}
