name: Vars
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose an env
        options:
        - stg
        - dev
env:
  RUNNER_VAR: ${{ vars.DEPLOY_RUNNER }} # This variable is available to all jobs      
jobs:
  display-variables:
    runs-on: ${{ env.RUNNER_VAR }}
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - name: Use variables
      run: |
        echo "deployment runner : ${{ vars.DEPLOY_RUNNER }}"
